// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShootingStarsController from "./shooting_stars_controller"
application.register("shooting-stars", ShootingStarsController)

import StarsBackgroundController from "./stars_background_controller"
application.register("stars-background", StarsBackgroundController)

import HeroAnimationController from "./hero_animation_controller"
application.register("hero-animation", HeroAnimationController)
